/*
 AUTOGENERATED FILE originally committed with concrete values.
 This file now reads from Vite environment variables with the original
 values preserved as fallbacks for local development. For production,
 prefer setting the VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_ANON_KEY
 environment variables in your host/CI (Vercel/Netlify/Supabase/etc.).
*/

// This file expects both values to be provided via Vite environment variables.
// Do NOT commit secrets to source. Set these in your host/CI (Vercel/Netlify/GitHub Actions).
// Example env names: VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_ANON_KEY

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string;

export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// Optional runtime sanity check (will log a clear error in the browser if missing)
if (!projectId || !publicAnonKey) {
	// eslint-disable-next-line no-console
	console.error('Missing Supabase environment variables: VITE_SUPABASE_PROJECT_ID or VITE_SUPABASE_ANON_KEY');
}