/*
 AUTOGENERATED FILE originally committed with concrete values.
 This file now reads from Vite environment variables with the original
 values preserved as fallbacks for local development. For production,
 prefer setting the VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_ANON_KEY
 environment variables in your host/CI (Vercel/Netlify/Supabase/etc.).
*/

const FALLBACK_PROJECT_ID = "mkblwhxlrdcoflliwnyr";
const FALLBACK_PUBLIC_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYmx3aHhscmRjb2ZsbGl3bnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNzEyNDksImV4cCI6MjA3NTk0NzI0OX0.CaK3tqR_p_sUcnlPohGq1ppZJI1HgrwLbNvrEgyrTvY";

// Read from Vite env vars (prefixed with VITE_). import.meta.env values are
// replaced at build time. Use these in CI/hosting instead of committing keys.
export const projectId = (
	import.meta.env.VITE_SUPABASE_PROJECT_ID as string
) || FALLBACK_PROJECT_ID;

export const publicAnonKey = (
	import.meta.env.VITE_SUPABASE_ANON_KEY as string
) || FALLBACK_PUBLIC_ANON_KEY;