/*
 AUTOGENERATED FILE originally committed with concrete values.
 This file now reads from Vite environment variables with the original
 values preserved as fallbacks for local development. For production,
 prefer setting the VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_ANON_KEY
 environment variables in your host/CI (Vercel/Netlify/Supabase/etc.).
*/

// Fallback values for when env vars are not set (GitHub Pages deployment)
const FALLBACK_PROJECT_ID = 'oexhltmmtcplmzxeymio';
const FALLBACK_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9leGhsdG1tdGNwbG16eGV5bWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjYxMDMsImV4cCI6MjA3Nzk0MjEwM30.V5aYoVo9FRgS3D2uAYAVyqZHsz3CSOE-CTo2DHjW5t8';

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || FALLBACK_PROJECT_ID;

export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || FALLBACK_ANON_KEY;

// Optional runtime sanity check (will log a clear error in the browser if missing)
if (!projectId || !publicAnonKey) {
	// eslint-disable-next-line no-console
	console.error('Missing Supabase environment variables: VITE_SUPABASE_PROJECT_ID or VITE_SUPABASE_ANON_KEY');
}